In [2]:
import torch
from torch import optim
from torch.optim import Adam
from tqdm import tqdm

from utils.data import read_domain_ids_per_chain_from_txt
from utils.dataset import *
from diffusion_model.sequence_diffusion_model import *

In [3]:
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
EPOCH = 100
LEARNING_RATE = 1e-3

In [4]:
train_pdbs, train_pdb_chains = read_domain_ids_per_chain_from_txt('./data/train_domains.txt')
test_pdbs, test_pdb_chains = read_domain_ids_per_chain_from_txt('./data/test_domains.txt')

In [5]:
train_loader = BackboneCoordsDataLoader(train_pdb_chains, "./data/train_backbone_coords_20.npy", "./data/train_data_res_20.npy",seq_length=20, batch_size=128, shuffle=True)
test_loader = BackboneCoordsDataLoader(test_pdb_chains, './data/test_backbone_coords_20.npy', './data/test_data_res_20.npy', seq_length=20, batch_size=128, shuffle=True)

In [23]:
for batch_idx, (pdb, res_label, atom_coords) in enumerate(tqdm(train_loader, leave=False)):
    
    break

torch.Size([128, 20])
tensor([[13,  7, 12,  ..., 12,  5, 12],
        [ 7,  5,  4,  ..., 11, 14,  3],
        [13, 12, 11,  ..., 11, 14,  1],
        ...,
        [13,  9, 14,  ...,  9, 19,  1],
        [ 4, 10,  8,  ..., 11,  2, 11],
        [ 0, 15,  4,  ..., 16,  2, 11]], dtype=torch.int32)
mask probability shape:  torch.Size([128, 20])
tensor([0.3600, 0.3600, 0.3600, 0.3600, 0.3600, 0.3600, 0.3600, 0.3600, 0.3600,
        0.3600, 0.3600, 0.3600, 0.3600, 0.3600, 0.3600, 0.3600, 0.3600, 0.3600,
        0.3600, 0.3600])
tensor([False, False,  True, False, False, False, False,  True, False,  True,
        False, False,  True,  True,  True,  True, False,  True,  True, False])
tensor([13,  7, 21, 12,  6, 10,  6, 21,  7, 21,  4,  1, 21, 21, 21, 21, 18, 21,
        21, 12], dtype=torch.int32)
tensor([-1, -1, 12, -1, -1, -1, -1, 11, -1, 13, -1, -1, 15,  7, 14, 11, -1, 12,
         5, -1], dtype=torch.int32)
